"""Create UserProfile table

Revision ID: 07e3172b2f23
Revises: e68495b3b2f6
Create Date: 2025-08-20 18:15:44.224316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added for SQLModel types in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '07e3172b2f23'
down_revision: Union[str, None] = 'e68495b3b2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('superpower', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kryptonite', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userprofile')
    # ### end Alembic commands ###
